# Generated by Django 4.2.5 on 2023-10-02 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinguser',
            name='description',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='thinguser',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='thinguser',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be at least 0.'), django.core.validators.MaxValueValidator(100, message='Value must be at most 100.')]),
        ),
    ]
