# Generated by Django 4.2.5 on 2023-10-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0002_alter_thinguser_description_alter_thinguser_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThingUser',
            new_name='Thing',
        ),
    ]
